hoge/config/routes.rb
Hoge::Application.routes.draw do
	match "announces/log/(:id)", :to => 'announces#log', :as => "log_announce"
  resources :announces
  match "announces/:id/start", :to => 'announces#start', :as => "start_announce"
	match "announces/:id/report", :to => 'announces#report', :as => "report_announce"
	match "announces/:id/finish", :to => 'announces#finish', :as => "finish_announce"
  match "announces/:id/result", :to => 'announces#result', :as => "result_announce"

end

hoge/app/models/announce.rb
class Announce < ActiveRecord::Base
	belongs_to :state
  attr_accessible :title, :device, :etime, :mail, :message, :name, :stime, :tel, :state_id
  validates :name, 	:presence => true
  validates :tel,	:presence => true
  validates :device,	:presence => true
	scope :working, where("state_id = 1")
	scope :finished, where("state_id = 3")
  scope :not_finished, where("NOT state_id = 3")
	scope :last_24_hours, lambda{
		where("etime > ?", 24.hours.ago ) 
	}

end

hoge/app/models/announce_observer.rb
class AnnounceObserver < ActiveRecord::Observer
  def after_save(announce)
#    AnnounceMailer.ack_email(announce).deliver
  end
end

hoge/app/models/state.rb
class State < ActiveRecord::Base
	has_many :announces, :foreign_key => 'state_id'
  attr_accessible :id, :state
end

hoge/app/controllers/announces_controller.rb
# coding: utf-8
class AnnouncesController < ApplicationController
	respond_to :html, :json

  # GET /announces
  # GET /announces.json
  def index
    @announces = Announce.not_finished.order("stime DESC")
		@pannounces = Announce.finished.last_24_hours.limit(20).order("etime DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announces }
    end
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
    @announce = Announce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/new
  # GET /announces/new.json
  def new
    @announce = Announce.new
		@type = params[:type]
		
		if @type == "fw" then
			@announce.title  = FW_TITLE
			@announce.device = FW_DEVICE 
			@announce.message = FW_MESSAGE
		elsif @type == "mac" then
			@announce.title = MAC_TITLE
			@announce.device = MAC_DEVICE
 			@announce.message = MAC_MESSAGE
		elsif @type == "room" then
			@announce.title = ROOM_TITLE
			@announce.message = ROOM_MESSAGE
		end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announce }
    end
  end

  # GET /announces/1/edit
  def edit
    @announce = Announce.find(params[:id])
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(params[:announce])

    respond_to do |format|
      if @announce.save
        format.html { redirect_to @announce, notice: 'Announce was successfully created.' }
        format.json { render json: @announce, status: :created, location: @announce }
      else
        format.html { render action: "new" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announces/1
  # PUT /announces/1.json
  def update
    @announce = Announce.find(params[:id])

    respond_to do |format|
      if @announce.update_attributes(params[:announce])
        format.html { redirect_to @announce, notice: 'Announce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce = Announce.find(params[:id])
    @announce.destroy
    #AnnounceMailer.delete_mail(@announce).deliver

    respond_to do |format|
      format.html { redirect_to announces_url }
      format.json { head :no_content }
    end
  end

  # /announces/1
  def start
    @announce = Announce.find(params[:id])
    AnnounceMailer.start_mail(@announce).deliver

		@announce.state_id = 1
		
		@announce.update_attributes(params[:announce])
		respond_with(@announce)
  end

	def report
		@announce = Announce.find(params[:id])
	end

	def result
		@announce = Announce.find(params[:id])
		@action = params[:aname]
		@message = params[:message]

		if @action == "report" then
			AnnounceMailer.report_mail(@announce, @message).deliver
		elsif @action == "finish" then
			AnnounceMailer.finish_mail(@announce, @message).deliver
			@announce.state_id = 3
		end

		@announce.update_attributes(params[:announce])
		respond_to do |format|
			if @action == "report" then
				format.html { render :action => :result }
			elsif @action == "finish" then
				format.html { render :action => :finish }
			end
		end
	end

	def finish
		@announce = Announce.find(params[:id])
		respond_to do |format|
			format.html { render :action => :report }
		end
	end

	def log
		@search = Announce.search(params[:search])
		@announces = @search.order("stime DESC").finished.page(params[:page]).per(10)
#		@announces = Announce.finished.order("stime DESC").page(params[:page]).per(10)
		respond_to do |format|
			format.html
			format.json { render json: @announces }
		end
	end
end

hoge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

hoge/app/helpers/announces_helper.rb
module AnnouncesHelper
end

hoge/app/helpers/application_helper.rb
module ApplicationHelper
end

hoge/app/views/announces/_form.html.erb
<%= form_for(@announce) do |f| %>
  <% if @announce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announce.errors.count, "error") %> prohibited this announce from being saved:</h2>

      <ul>
      <% @announce.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%
		if @announce.state_id.present?
			status = @announce.state_id
		else
			status = 0
		end
	%>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :mail %>
		(You can use commas to separate multiple addresses.)<br />
		(This address is used for CC address. TO address is cloc-ia -at- nttcloud.net, so you don't need for write it.)<br />
    </br>
		<%= f.text_field :mail %>
  </div>
  <div class="field">
    StartTime<br />
    <%= f.datetime_select :stime %>
  </div>
  <div class="field">
    EndTime<br />
    <%= f.datetime_select :etime %>
  </div>
  <div class="field">
    <%= f.label :device %><br />
    <%= f.text_area :device, :size => "40x5", :class => "span5" %>
  </div>
	<%= f.hidden_field :state_id, :value => status %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :class => "span5" %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hoge/app/views/announces/_messageform.html.erb
<%= form_tag('result') do %>
  <div class="field">
    <%= text_area_tag :message, '', :size => "40x10", :class => 'span5' %>
  </div>
	
	<%= hidden_field_tag :aname, action_name %>

	<div class="actions">
    <%= submit_tag("Send Message") %>
  </div>
	
<% end %>

hoge/app/views/announces/edit.html.erb
<h1>Editing announce</h1>

<%= render 'form' %>

<%= link_to 'Show', @announce %> |
<%= link_to 'Back', announces_path %>

hoge/app/views/announces/finish.html.erb
<h1>Transmission Complete.</h1>

Announce mail has sent and construction status has changed from "Working" to "Finish".
<br />

Your announce is as follows,

<hr>
<pre>
Title: <%= MAIL_SUBJ_FINISH+@announce.title %>

CLOC各位
Dear CLOC members,

お疲れ様です。
以下の作業は完了いたしました。
何か問題があればご連絡ください。
This email is to inform you that we have finished to work on CLOUD NW/server devices.
Please contact us, if there are any problems.

<%= params[:message] %>

=========================================
devices          : <%= @announce.device %>
operator         : <%= @announce.name %>
operation time   : <%= @announce.stime.to_s(:simple) %> - <%= @announce.etime.to_s(:simple) %>
emergency contact: <%= @announce.tel %>
start messages   :
<%= @announce.message %>
=========================================

以上、よろしくお願いいたします。
Regards,

-- Sent from construction announce system --
</pre>
<hr>

<%= link_to 'Show', @announce %> |
<%= link_to 'Back', announces_path %>

hoge/app/views/announces/index.html.erb
<h2>Latest Announces</h2>

<table class="table table-striped">
  <tr>
    <th>Status</th>
    <th>Title</th>
    <th>Name</th>
    <th>Tel</th>
    <th>Mail</th>
    <th>StartTime</th>
    <th>EndTime</th>
    <th>Device</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

	<% @announces.each do |announce| %>
	<tr>
    <td><%= announce.state.state %></td>
    <td><%= announce.title %></td>
    <td><%= announce.name %></td>
    <td><%= announce.tel %></td>
    <td><%= announce.mail %></td>
    <td><%= announce.stime.to_s(:simple) %></td>
    <td><%= announce.etime.to_s(:simple) %></td>
    <td><%= announce.device %></td>
    <td><%= announce.message %></td>
    <% if announce.state_id == 0 then %>
    <td colspan = 2><%= link_to 'Start', start_announce_path(announce), :class => "btn btn-mini" %></td>
    <% elsif announce.state_id == 1 || announce.state_id == 2 then %>
    <td><%= link_to 'Report', report_announce_path(announce), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Finish', finish_announce_path(announce), :class => "btn btn-mini" %></td>
    <% else %>
    <td colspan=2></td>
    <% end %>
    <% if announce.state_id == 0 then %>
    <td><%= link_to 'Edit', edit_announce_path(announce), :class => "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', announce, method: :delete, confirm: 'Are you sure?', :class => "btn btn-mini" %></td>
    <% else %>
    <td colspan = 2></td>
    <% end %>
  </tr>
	<% end %>
</table>


<h2>Past Announces(Last 24 Hours)</h2>

<table class="table table-striped">
  <tr>
    <th>Status</th>
    <th>Title</th>
    <th>Name</th>
    <th>Tel</th>
    <th>Mail</th>
    <th>StartTime</th>
    <th>EndTime</th>
    <th>Device</th>
    <th>Message</th>
  </tr>

<% @pannounces.each do |announce| %>
  <tr>
    <td><%= announce.state.state %></td>
    <td><%= announce.title %></td>
    <td><%= announce.name %></td>
    <td><%= announce.tel %></td>
    <td><%= announce.mail %></td>
    <td><%= announce.stime.to_s(:simple) %></td>
    <td><%= announce.etime.to_s(:simple) %></td>
    <td><%= announce.device %></td>
    <td><%= announce.message %></td>
  </tr>
<% end %>
</table>

hoge/app/views/announces/log.html.erb
<h1>Past Announces</h1>

<%= form_for @search, :url => log_announce_path do |f| %>
	<%= f.label "Start Date" %>
	<%= f.date_select :stime_gte, :default => Date.yesterday %>
	<%= f.label "End Date"%>
	<%= f.date_select :etime_lte %></br>
	<%= f.submit "search" %>
<% end %>

<table class="table table-bordered table-striped">
  <tr>
    <th>Status</th>
    <th>Title</th>
    <th>Name</th>
    <th>Tel</th>
    <th>Mail</th>
    <th>StartTime</th>
    <th>EndTime</th>
    <th>Device</th>
    <th>Message</th>
  </tr>

<% @announces.each do |announce| %>
  <tr>
    <td><%= announce.state.state %></td>
    <td><%= announce.title %></td>
    <td><%= announce.name %></td>
    <td><%= announce.tel %></td>
    <td><%= announce.mail %></td>
    <td><%= announce.stime.to_s(:simple) %></td>
    <td><%= announce.etime.to_s(:simple) %></td>
    <td><%= announce.device %></td>
    <td><%= announce.message %></td>
  </tr>
<% end %>
</table>

<%= paginate @announces %>

hoge/app/views/announces/new.html.erb
<h1>New Info.</h1>

<%= render 'form' %>

<%= link_to 'Back', announces_path %>

hoge/app/views/announces/report.html.erb
<h1>Reporting Message</h1>

<%= render 'messageform' %>

<h2>Related Construction Infomation</h2>

<div>
<p>
  <b>Name:</b>
  <%= @announce.name %>
</p>

<p>
  <b>Tel:</b>
  <%= @announce.tel %>
</p>

<p>
  <b>Mail:</b>
  <%= @announce.mail %>
</p>

<p>
  <b>StartTime:</b>
  <%= @announce.stime.to_s(:simple) %>
</p>

<p>
  <b>EndTime:</b>
  <%= @announce.etime.to_s(:simple) %>
</p>

<p>
  <b>Device:</b>
  <%= @announce.device %>
</p>

<p>
  <b>Message:</b>
  <%= @announce.message %>
</p>
</div>

<%= link_to 'Back', announces_path %>

hoge/app/views/announces/result.html.erb
<h1>Transmission Complete.</h1>

Report mail has sent.
<br />

Your announce is as follows,

<hr>
<pre>
Title: <%= MAIL_SUBJ_REPORT+@announce.title %>

CLOC各位
Dear CLOC members,

お疲れ様です。
掲題の作業について、以下の状況となっておりますためご連絡いたします。
追って続報をお送りいたします。
This email is to inform you that the following situations occured during construction.
We will send a follow-up later on.

<%= params[:message] %>

=========================================
devices          : <%= @announce.device %>
operator         : <%= @announce.name %>
operation time   : <%= @announce.stime.to_s(:simple) %> - <%= @announce.etime.to_s(:simple) %>
emergency contact: <%= @announce.tel %>
start messages   :
<%= @announce.message %>
=========================================

以上、よろしくお願いいたします。
Regards,

-- Sent from construction announce system --
</pre>
<hr>

<%= link_to 'Show', @announce %> |
<%= link_to 'Back', announces_path %>

hoge/app/views/announces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @announce.name %>
</p>

<p>
  <b>Tel:</b>
  <%= @announce.tel %>
</p>

<p>
  <b>Mail:</b>
  <%= @announce.mail %>
</p>

<p>
  <b>StartTime:</b>
  <%= @announce.stime.to_s(:simple) %>
</p>

<p>
  <b>EndTime:</b>
  <%= @announce.etime.to_s(:simple) %>
</p>

<p>
  <b>Device:</b>
  <%= @announce.device %>
</p>

<p>
  <b>Message:</b>
  <%= @announce.message %>
</p>


<%= link_to 'Edit', edit_announce_path(@announce) %> |
<%= link_to 'Back', announces_path %>

hoge/app/views/announces/start.html.erb
<h1>Transmission Complete.</h1>

Announce mail has sent and construction status has changed from "StandBy" to " 
<%= @announce.state.state %>".
<br />

Your announce is as follows,

<hr>
<pre>
Title: <%= MAIL_SUBJ_START+@announce.title %>

CLOC各位
Dear CLOC members,

お疲れ様です。
只今より掲題の件で作業を行います。
詳細は以下の通りです。
This email is to inform you that we intend to work on CLOUD NW/server devices.
The details are as follows:

<%= @announce.message %>

=========================================
devices          : <%= @announce.device %>
operator         : <%= @announce.name %>
operation time   : <%= @announce.stime.to_s(:simple) %> - <%= @announce.etime.to_s(:simple) %>
emergency contact: <%= @announce.tel %>
=========================================

以上、よろしくお願いいたします。
Regards,

-- Sent from construction announce system --
</pre>
<hr>

<%= link_to 'Show', @announce %> |
<%= link_to 'Back', announces_path %>

hoge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CLOC Construction Information System</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap.min" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div style="background:#DCDCDC; ">
    <img src="/announces/assets/Construction Info.png" style="width:380px; height:38px; margin-left:40px; margin-top:0px;">
    </br>
    <p class="lead" style="font-size: 100%; text-indent: 40px;">CLOC construction infomation about NW nodes, links, configrations, and more.</p>
  </div>
</header>

  <div class="row-fluid">

    <div class="span1">
      </br>
        <ul class="nav nav-list bs-docs-sidenav">
        <li><button class="btn btn-small btn-danger" type="button" onClick="location.href='<%=new_announce_path%>'">new info.</button></li>
        <li><%= link_to 'Top', announces_path %></li>
        <li><%= link_to 'Log', log_announce_path %></li>
				</ul>
				</br>
				<ul class="nav nav-list bs-docs-sidenav">
        	<li><%= link_to 'FW Config Announce', :action => :new, :type => 'fw' %></li>
					<li><%= link_to 'MAC Filter Announce', :action => :new, :type => 'mac' %></li>
					<li><%= link_to 'VLAN Change Announce', :action => :new, :type => 'room' %></li>
				</ul>
    </div>

    <div class="span11">
     <%= yield %>
    </div>

   </div>

</body>
</html>